#!/usr/bin/env ansible-playbook
---
# Run system tests against a hardened system
- include: playbooks/operations/ping.yml
- include: playbooks/security/fips_check.yml

- name: Check access to internal registry
  hosts: all
  tasks:
    - uri:
        url: http://ocp-registry.lab.revoweb:5000/v2/_catalog
        return_content: yes
      register: registrypage
    - name: Verify registry catalog is not empty
      fail:
      when: "'repositories' not in registrypage.content"

- name: "Check access to docker-registry-default"
  hosts: all
  tasks:
    - uri:
        url: "https://docker-registry-default.{{ default_subdomain }}/"
        validate_certs: no
        return_content: yes

- name: "Check access to registry-console-default"
  hosts: all
  tasks:
    - uri:
        url: "https://registry-console-default.{{ default_subdomain }}/"
        validate_certs: no
        return_content: yes

- name: Check if reference-project is installed
  hosts: localhost
  tasks:
    - name: Check if reference-project is installed
      shell: |
        if [ `oc projects -q | grep 'reference-project'` ]; then echo true; else echo false; fi
      register: reference_project_available
      when: check_reference_project

- name: Validate Reference Project
  hosts: localhost
  tasks:
    - name: Validate Reference Project
      include_role:
        name: reference_project_validation
      when: reference_project_available and check_reference_project

- name: Check Node health
  hosts: masters[0]
  tasks:
    - name: Check Node Health
      shell: oc get nodes
      register: nodes_shell_result
      failed_when: "'Not' in nodes_shell_result.stdout"

    - name: Show result of 'oc get nodes'
      debug:
        var: nodes_shell_result

    - name: Check ETC Health
      shell: etcdctl --cert-file=$ETCD_PEER_CERT_FILE --key-file=$ETCD_PEER_KEY_FILE --ca-file=/etc/etcd/ca.crt --endpoints=$ETCD_LISTEN_CLIENT_URLS cluster-health 
      register: etcd_shell_result
      failed_when: "'Something' in etcd_shell_result.stdout"
  


- name: Check API service and web console
  hosts: localhost
  tasks:
    - name: Check the healthz endpoint for OCP masters
      uri:
        url: "{{ masters_route }}:{{ api_port }}/healthz"
        method: GET
        validate_certs: no
        status_code: 200
        return_content: yes
      register: healthz_api_response
      failed_when: "'OK' not in healthz_api_response"

